# Generated by Django 4.2.13 on 2024-07-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_group_students_alter_group_leader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
