# Generated by Django 4.2.13 on 2024-06-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="firs_name",
            new_name="first_name",
        ),
    ]
